### ISSUE TITLE
[SUGGESTION] Guardian Lasers

### ISSUE THREAD

**Issue by GoldenMyst** [Ankoki-Dev/SkJade#11]
**Describe what you want added**
A way to create guardian lasers from a certain position to another.

**Proposed Syntax**
`create guardian laser from %location% to %location with id %string%'

**Skript?**

**Comment by Ankoki** [comment]
Already in progress. They have been for a while, there is just one bug to squash until they're ready for release.

**Comment by Ankoki** [comment]
Added in the 1.3.1 release

**Comment by Psekk** [comment]
Your mom... that nearly took 2 months u tit
