### ISSUE TITLE
[ISSUE] Hologram Line expression

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [Ankoki-Dev/SkJade#12]
**Describe the issue**
I am trying to get the lines of a hologram, and i use `set {_blockLines::*} to all lines of the hologram with id "BlocksLB"` (straight from the docs with slight modification, and when I put that in my script, the script stops. There is no error on reload.

**Expected behavior**
It sets the variable to the lines of the hologram

**To Reproduce**
Create a hologram, then put `set {_blockLines::*} to all lines of the hologram with id "BlocksLB"` and some code after it (a send or broadcast would work best imo).

**Information**
Server Version: Paper 1.16.5
SkJade Version: 1.3.0

**Additional context**
None

**Comment by Ankoki** [comment]
I've seen a fair few issues with hologram lines recently, i shall have a look into it
