### ISSUE TITLE
[SUGGESTION] Item Cooldown for Multiple Items

### ISSUE THREAD

**Issue by EarthAgar** [Ankoki-Dev/SkJade#13]
**Describe what you want added**
Add support to add cooldowns to multiple items at once. The would make things easier and help us avoid loops.

**Proposed Syntax**
`set the cooldown of {_items::*} for player to 1 second`
`set the cooldown of all pickaxes for player to 3 second`
`set the cooldown of all wool for player to 15 second`

**Skript?**
If you have created this in skript as a replica, feel free to drop your script here to make my job easier!
```
on place:
	loop all items in player's inventory where [input is a block]:
		set the cooldown of loop-item for player to 1 second
```

**Comment by Ankoki** [comment]
Will work on adding this!
