### ISSUE TITLE
[ISSUE] when it's <times> not working.

### ISSUE THREAD

**Issue by ZustFancake** [Ankoki-Dev/SkJade#17]
**Describe the issue**
When i try to write `when it's <times>' to my skript, it's not working. since i tried to replace it with GMT time, but it's not working. and i tried to replace it with system/server time, but still not working.

**Expected behavior**
when i do
`when it's 08:00am in real world:
    restart server`
, server should restart at 08:00am ( 11:00pm GMT ).

**To Reproduce**
`when it's 08:00am in real world:
    restart server
#not working

when it's 11:00pm GMT:
    restart server
#still not working
`

**Information**
Give us your server version, platform, and SkJade version.
server platform & version = paper-1.17.1-116
Skjade = latest.

**Additional context**
None

**Comment by Ankoki** [comment]
as far as im aware, the time is GMT, try just doing 11:00pm

**Comment by ZustFancake** [comment]
i tried make it run at 03:00pm GMT ( 12:00am in server time ), still not working.

`when it's 03:00pm GMT:
   broadcast "hi"`

**Comment by Ankoki** [comment]
Just had a look at this, 
```vb
when it's 16:17 irl:
	broadcast "Hey its 16:18!"
``` 
Using this code, 
![image](https://user-images.githubusercontent.com/72931234/126815470-44e55dcd-06a1-4b73-bd81-cc7045729223.png)
it broadcasts correctly, however i live in england and this did in fact broadcast at 17:17 my time
