### ISSUE TITLE
[ISSUE] Condition "player is in rain or bubble column" is not working in most recent 1.17 version (SkJade 1.3.3)

### ISSUE THREAD

**Issue by Bugin4** [Ankoki-Dev/SkJade#18]
**Describe the issue**

Condition "player is in rain or bubble column" is not working in most recent 1.17 version (SkJade 1.3.3)
ERROR: "Can't compare a player with ('in rain' or 'bubble column')"

I tried:

player is in rain
player is in bubble column
player is standing in rain
player is standing in bubble column
player is in rain or bubble column
player is standing in rain or bubble column

**Expected behavior**

Condition should not give errors
This condition was working in 1.16 version

**To Reproduce**

command /test:
   trigger:
      if player is in rain or bubble column:
         broadcast "yes"

**Information**

paper-1.17.1-137
SkJade 1.3.3

**Comment by Ankoki-Dev** [comment]
are there any exceptions in the console?

**Comment by Ankoki** [comment]
I'm not going to look into this issue in favour of https://github.com/SkriptLang/Skript/pull/4184.

**Comment by Bugin4** [comment]
Is that condition already added to 2.6-beta2 or are they working on it?

**Comment by bluelhf** [comment]
They are working on it
