### ISSUE TITLE
[ISSUE] conflict with SkBee

### ISSUE THREAD

**Issue by ShaneBeee** [Ankoki-Dev/SkJade#19]
**Describe the issue**
I recently created a new structure system in Skript, and the registered ClassInfo for the class Structure.class, I used the code name "structure", this conflicts with SkJade also using "structure":
https://github.com/Ankoki-Dev/SkJade/blob/683e2acb05fded1a4386dfc161670369aa60f820/src/main/java/com/ankoki/skjade/utils/NonLegacyClassInfo.java#L14
I wanted to suggest changing that, since "structure" does not properly match StructureType and clearly conflicts with SkBee, and potentially other addons.

**Comment by Ankoki** [comment]
ah i see, i'll make that change as soon as i'm next at my computer:)

**Comment by Ankoki** [comment]
ah i now remeber as to why this was "structure" and not "structuretype", that alias is already in skript, i shall now change this to "skjstructuretype" XD
