### ISSUE TITLE
skript-holo conflict

### ISSUE THREAD

**Issue by EarthAgar** [Ankoki-Dev/SkJade#2]
When I remove skript-holo from my server the plugin will enable fine.

Here is the console error: [https://paste.helpch.at/iwatosumul.md](https://paste.helpch.at/iwatosumul.md)

Versions for all associated plugins:
![image](https://user-images.githubusercontent.com/27425322/108258238-a7986880-7114-11eb-8b81-6e8408fece2d.png)

**Comment by Ankoki** [comment]
I see why this occurs, i'll work on adding a config where you can disable certain elements such as the holographic displays so this doesn't happen, though you shouldn't need both, unless skript-holo provides something SkJade doesn't.

**Comment by EarthAgar** [comment]
Yeah the reason I want to use skript-holo is because it provides following holograms which are quite nice and useful.

**Comment by Ankoki** [comment]
ah got you, i'll work on the config tomorrow, the error should be able to be ignored and not cause any problems until i've added the config c:

**Comment by Ankoki** [comment]
Config has been added so that you can disable the holographic displays elements to stop this from happening c:
