### ISSUE TITLE
[ISSUE] Item cooldown visuals are bugged on death

### ISSUE THREAD

**Issue by Pryzmm** [Ankoki-Dev/SkJade#23]
**Describe the issue**
The item cooldown visual effect is removed when the player dies, but the countdown still continues

**Expected behavior**
The countdown should reset on death or the visual doesnt reset on death

**To Reproduce**
```
# Execute /test1, place the block, then /test2

command /test1:
	trigger:
		give player white wool named "Place Me!"

command /test2:
	trigger:
		send the cooldown of white wool for player

on place of white wool:
	cancel event
	set the cooldown of white wool for player to 10 minutes
	send "Commiting die in 5 seconds" to player
	wait 5 seconds
	kill player
```

**Information**
Server Version: 1.17.1
Platform: Java
Skript Version: Latest (2.6.1)
SkJade Version: Latest (1.4.1)

**Comment by Ankoki** [comment]
unfortunately the method I use is provided by spigot/paper, so this should be an issue bought up with them.
