### ISSUE TITLE
[ISSUE] Hologram remove line does not work.

### ISSUE THREAD

**Issue by Warpedtimes** [Ankoki-Dev/SkJade#24]
**Describe the issue**
I have a hologram and would like to remove a line from it. 
Using this syntax `remove line 2 from the hologram with the id "hologramID"` successfully reloads but as soon as the event where the line is meant to be removed is called nothing happens and I get an error.

**Expected behavior**
I except the line to have been removed.

**To Reproduce**
```
command test:
    trigger:
        create a hologram at location of player with the id "hologramID"
        add line "Lines Number 1" to the hologram with id "hologramID"
        add line "Line Number 2" to the hologram with id "hologramID"
        wait 5 seconds
        remove line 2 from the hologram with id "hologramID"
```

**Information**
Give us your server version, platform, and SkJade version.
1.18.2, Paper, SkJade: 1.4.1

Error:
[Error.txt](https://github.com/Ankoki/SkJade/files/8775123/Error.txt)

**Comment by Ankoki** [comment]
i'm currently reworking holograms in 2.0, but i'll make sure to release a patch to fix this once i am home
