### ISSUE TITLE
All skript events are no longer available.

### ISSUE THREAD

**Issue by puzupuzu** [Ankoki-Dev/SkJade#25]
Currently my server version is spigot=1.17.1, plugin versions are `skript=2.6.2, Disky=4.0-beta4, skrayfall=1.9.27, skript-reflect=2.3, skript-yaml=1.4, skutilities=0.9.2, skbee=1.15.3, skimage=1.8, skquery=4.1.1 skutilities=0.9.2, skbee=1.15.3, skimage=1.8, skquery=4.1.6, skript-packet=2.1.0.`
I would love to use this great plugin!

**Comment by Ankoki** [comment]
i'll need a little more info than this:) can you send any big errors in console?

**Comment by puzupuzu** [comment]
[err.txt](https://github.com/Ankoki/SkJade/files/8861441/err.txt)
There were about 5 errors of this nature.

**Comment by Ankoki** [comment]
try disabling the hologram hook in the config then restart your server

**Comment by puzupuzu** [comment]
Resolved!!! Thank you!
