### ISSUE TITLE
On Async PreLogin Event - Expressions and Effects

### ISSUE THREAD

**Issue by aircacti** [Ankoki-Dev/SkJade#28]
Hello. I have seen that you provide ["On Async PreLogin"](https://docs.skunity.com/syntax/search/from:skjade%20pre%20login) event that works as Java AsyncPlayerPreLoginEvent, but i haven't seen any way to deal with event-player in documentation available in skunity. 

What kind of effects and expressions does offer that event? Is there any way to do something like
`event.disallow(AsyncPlayerPreLoginEvent.Result.KICK_BANNED, "You cant join");` by using your SkJade addon?

Thanks in advance.

**Comment by Ankoki** [comment]
Hi! You cannot add a custom string to the end, however you can set `event-login-result` to any of the following:  
`"kick other"`
`"allowed"`
`"kick banned"`
`"kick full"`
`"kick whitelist"`
Do note they must be strings :)

**Comment by aircacti** [comment]
Thank you very much
