### ISSUE TITLE
[ISSUE] IRL Time misleading syntax

### ISSUE THREAD

**Issue by sovdeeth** [Ankoki-Dev/SkJade#29]
**Describe the issue**
The event `at x irl|gmt|in real life` does not behave as expected. The event only triggers based on local server time, even when using `GMT` in the syntax. 

**Expected behavior**
I expected it to trigger at local time when using `irl` or `in real life`, and at GMT time when using `GMT`.

**To Reproduce**
Hard to test if you're in GMT, but just use two times that should be identical. This is for EST.
```
at 01:53 GMT:
    broadcast "test gmt (%now%)"

at 20:53 irl:
    broadcast "test est (%now%)"
```
![image](https://user-images.githubusercontent.com/10354869/206823404-1930fc04-7fad-410f-88bf-dfd6ec7beced.png)

**Information**
Paper 1.19.2, Skript 2.6.3 (structure API), SkJade 1.4.2
![image](https://user-images.githubusercontent.com/10354869/206823318-5df346e2-d701-451e-a777-963fd14a7a5f.png)

**Additional context**
Looks like there just isn't any difference in the code between using GMT and IRL. Perhaps this is intentional, and if so, I think the GMT syntax should be removed as it's misleading.

**Comment by Ankoki** [comment]
i feel like i should change the GMT to sever time, it was GMT when i tested but i live in Scotland so it makes sense when it's GMT, it wil execute when the JVM is at the time, i'll make sure to change it with 2.0 !!!!!
