### ISSUE TITLE
[suggestion] ImageMessage

### ISSUE THREAD

**Issue by DampfWaffel** [Ankoki-Dev/SkJade#3]
Hello,

is it possible to add the [ImageMessage](https://bukkit.org/threads/204902/) to SkJade?
so with i.g <https://cravatar.eu/avatar/a2080281-c278-4181-b961-d99ed2f3347c.png> im able to recrate the image in the chat.
![image](https://user-images.githubusercontent.com/19693397/111216173-5d4fbd80-85d4-11eb-827a-986cb1b89b94.png)

: )

**Comment by Ankoki** [comment]
Sorry for the slow reply i don't really check here much, but this library is around 8 years old haha, i can look into it:)

**Comment by DampfWaffel** [comment]
yea. sadly i couldn't find a new version.
<https://www.spigotmc.org/resources/picture-login.4514/> there are some Plugins that use the Lib with this day.

**Comment by Ankoki** [comment]
ill still give it a look! i'll do some testing to see how it works:)

**Comment by Ankoki** [comment]
Technically this is added now with the addition of the image message syntax from holographic displays. Will still require holographic displays, however it returns a list of strings (string per line) so it can be manipulated to be used wherever!
