### ISSUE TITLE
[SUGGESTION] Default changes for `lines of %hologram%`

### ISSUE THREAD

**Issue by Fusezion** [Ankoki-Dev/SkJade#30]
**Describe what you want added**
Add the ability to set lines of a hologram. `set line 2 of hologram (holo) to ""` a friend ran into an issue where we wanted to set a line
but there was no code to do this

**Proposed Syntax**
simply an update to the 
```AppleScript
[all] [the] lines of %holograms% 
line %number% of [the] [holo[gram]] %hologram% 
event( |-)[holo[gram]][(-| )]line 
```
simply wanting to add changer support for lines 
``set, add, remove, delete``
```
add %strings% to lines of hologram (holo)
set line 2 of hologram (holo) to %string%
remove line 3 of hologram (holo) from lines of hologram (holo)
```

**Skript?**
If you have created this in skript as a replica, feel free to drop your script here to make my job easier!

**Comment by Fusezion** [comment]
did just find the `content of` but I feel like it should still be combined as 1 whole expression

**Comment by Ankoki** [comment]
In 2.0 this will be a combined expression, but the reason this was a seperate expression is people wanted to store the line itself sometimes (for some reason), but in 2.0 (which is very nearly ready) it will be a combined one.
