### ISSUE TITLE
[SUGGESTION] Show Entity

### ISSUE THREAD

**Issue by JerryTheSlime16** [Ankoki-Dev/SkJade#34]
**Describe what you want added**
The opposite of the pre-existing Hide Entity. This would act as a method to show a previously hidden entity.

**Proposed Syntax**
`[skjade] (show|reveal|unhide) [[the] entity] %entities% ((to|from) %players%|)`

**Comment by Ankoki** [comment]
It has been on my mind for a while, it's just a bit harder to construct the entity than it is to make it go poof, but it might be easier than i expect so i'll look into it for 2.0

**Comment by JerryTheSlime16** [comment]
All right; do you have any sort of timeline on when 2.0 will be released & when you will know if this will be a feature? If not that is okay.

**Comment by Ankoki** [comment]
Unfortunately i'm not quite sure as i'm waiting for a Skript PR to be merged, which depends on another PR 😭 i'll keep you updated here on any updates tho:)

**Comment by Ankoki** [comment]
I'm going to close this pr as I will not be doing this. The reason is that this "spawned" entity will not act like an actual entity, however just a dummy. They are not ticked as they are client sided so there is no real use for them, they will only be clones of what they once were.
