### ISSUE TITLE
[ISSUE] Update check still happens when update checker is disabled in config.

### ISSUE THREAD

**Issue by TwinkleToes777** [Ankoki-Dev/SkJade#37]
**Describe the issue**
Update check still happens when update checker is disabled in config.

**Expected behavior**
For SkJade to not do any internet connections.

**To Reproduce**
Observe network requests with plugin such as NetworkInterceptor
**Information**
1.16.5, SkJade 1.4.4

**Comment by Ankoki** [comment]
In 1.4.4 there is no config option to disable the update checler

**Comment by TwinkleToes777** [comment]
> In 1.4.4 there is no config option to disable the update checler

can you add it?
