### ISSUE TITLE
(Suggestion) Add line lists.

### ISSUE THREAD

**Issue by baylorhenshaw** [Ankoki-Dev/SkJade#5]
Currently, you cannot use a list variable with multiple strings, you have to add lines individually. I think it would be really nice to be able to use lists to avoid large blocks of code for multiple lines in a hologram.

Something like `add line {_lines::*} to the hologram with id "testHolo"` would be really nice!

**Comment by Ankoki** [comment]
this will be fairly easy to implement, and i will do as such:D

**Comment by Ankoki** [comment]
Added and tested so i can now close this, will be in the next release:)
