### ISSUE TITLE
(Suggestion) Show/Clear mining stages

### ISSUE THREAD

**Issue by kill05** [Ankoki-Dev/SkJade#6]
Hello, I'd like to suggest to add a syntax for the packet that shows block break animations, since the one already out are outdated and don't allow to reset the animation.
I'd imagine the syntax looking like:

show mining stage %number% at %location% to %players%
reset/clear mining stage at %location% for %players%

Thanks in advice for reading and I hope to see this implemented!

**Comment by Ankoki** [comment]
shouldn't be that hard, ill look into it:)

**Comment by kill05** [comment]
Thanks a ton ;)
